  CREATE TABLE EDUCATION_RESULT 
   ("STUDENT_CODE" NUMBER(5,0) NOT NULL ENABLE, 
	"ELECTIVE_CODE" NUMBER(6,0) NOT NULL ENABLE, 
	"ASSESSMENT" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "EDUCATION_RESULT_FK1" FOREIGN KEY ("STUDENT_CODE")
	  REFERENCES "SYSTEM"."STUDENTS" ("STUDENT_CODE") ENABLE, 
	 CONSTRAINT "EDUCATION_RESULT_FK2" FOREIGN KEY ("ELECTIVE_CODE")
	  REFERENCES "SYSTEM"."ELECTIVES" ("ELECTIVE_CODE") ENABLE
   );
   
  CREATE TABLE ELECTIVES
   (	"ELECTIVE_CODE" NUMBER(6,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BEGINNING_DATE" DATE NOT NULL ENABLE, 
	"VOLUME_LECTURES" NUMBER DEFAULT NULL, 
	"VOLUME_PRACTICES" NUMBER, 
	"VOLUME_LABWORK" NUMBER, 
	 CONSTRAINT "ELECTIVES_PK" PRIMARY KEY ("ELECTIVE_CODE"));

    
  CREATE TABLE ELECTIVES
   (	"ELECTIVE_CODE" NUMBER(6,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"BEGINNING_DATE" DATE NOT NULL ENABLE, 
	"VOLUME_LECTURES" NUMBER DEFAULT NULL, 
	"VOLUME_PRACTICES" NUMBER, 
	"VOLUME_LABWORK" NUMBER, 
	 CONSTRAINT "ELECTIVES_PK" PRIMARY KEY ("ELECTIVE_CODE"));
